version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp